version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./database/:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
